# Generated by Django 3.2 on 2022-01-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosaml2idp', '0002_persistent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='_disable_idp_initiated_login_in_response_to',
            field=models.BooleanField(help_text='If not set, default to False.', null=True, verbose_name='Disable IdP_Initiated_Login in response to'),
        ),
    ]
